# Generated by Django 4.1.7 on 2023-04-04 09:02

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('houseNumber', models.PositiveSmallIntegerField(default=0)),
                ('street', models.CharField(default='', max_length=50)),
                ('city', models.CharField(default='', max_length=50)),
                ('country', models.CharField(default='', max_length=50)),
                ('postalCode', models.CharField(default='', max_length=50)),
            ],
            options={
                'db_table': 'address',
                'ordering': ['country', 'city'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('password', models.CharField(default='', max_length=50)),
                ('email', models.EmailField(default='', max_length=254)),
                ('phone', models.CharField(default='', max_length=20)),
                ('familyName', models.CharField(default='', max_length=100)),
                ('typeClient', models.CharField(choices=[('NORMAL', 'Normal Customer'), ('LOYAL', 'Loyal Customer'), ('VIP', 'VIP Customer')], default='NORMAL', max_length=50)),
                ('address', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='e_commerce_app.address')),
            ],
            options={
                'db_table': 'clients',
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('password', models.CharField(default='', max_length=50)),
                ('email', models.EmailField(default='', max_length=254)),
                ('phone', models.CharField(default='', max_length=20)),
                ('site_url', models.URLField(default='')),
                ('address', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='e_commerce_app.address')),
            ],
            options={
                'db_table': 'providers',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='', max_length=100)),
                ('price', models.FloatField(default=0)),
                ('stock', models.PositiveSmallIntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/product_images')),
                ('description', models.TextField(blank=True, null=True)),
                ('expirationDate', models.DateField(default=datetime.date(2023, 12, 31))),
                ('fabricationDate', models.DateField(default=django.utils.timezone.now)),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='e_commerce_app.provider')),
            ],
            options={
                'db_table': 'products',
                'ordering': ['label', '-price'],
            },
        ),
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_cmd', models.DateField(default=django.utils.timezone.now)),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_commerce_app.client')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_commerce_app.product')),
            ],
            options={
                'verbose_name': 'Command table',
                'verbose_name_plural': 'Command List',
                'db_table': 'commands',
                'ordering': ['-date_cmd'],
                'unique_together': {('client', 'product', 'date_cmd')},
            },
        ),
        migrations.AddField(
            model_name='client',
            name='client_products',
            field=models.ManyToManyField(through='e_commerce_app.Command', to='e_commerce_app.product'),
        ),
    ]
